api_key = '579b464db66ec23bdd000001cbe3f36f700048854084fbab4711730e'
state_dict = {'Andhra Pradesh': 0,
              'Arunachal Pradesh': 1,
              'Assam': 2,
              'Bihar': 3,
              'Chandigarh': 4,
              'Chhattisgarh': 5,
              'Delhi': 6,
              'Goa': 7,
              'Haryana': 8,
              'Himachal Pradesh': 9,
              'Jharkhand': 10,
              'Karnataka': 11,
              'Kerala': 12,
              'Madhya Pradesh': 13,
              'Maharashtra': 14,
              'Manipur': 15,
              'Meghalaya': 16,
              'Mizoram': 17,
              'Nagaland': 18,
              'Puducherry': 19,
              'Punjab': 20,
              'Rajasthan': 21,
              'Sikkim': 22,
              'Tamil Nadu': 23,
              'Uttar Pradesh': 24,
              'Uttaranchal': 25,
              'West Bengal': 26
              }
state_dict_reverse = {0: 'Andhra Pradesh',
                      1: 'Arunachal Pradesh',
                      2: 'Assam',
                      3: 'Bihar',
                      4: 'Chandigarh',
                      5: 'Chhattisgarh',
                      6: 'Delhi',
                      7: 'Goa',
                      8: 'Haryana',
                      9: 'Himachal Pradesh',
                      10: 'Jharkhand',
                      11: 'Karnataka',
                      12: 'Kerala',
                      13: 'Madhya Pradesh',
                      14: 'Maharashtra',
                      15: 'Manipur',
                      16: 'Meghalaya',
                      17: 'Mizoram',
                      18: 'Nagaland',
                      19: 'Puducherry',
                      20: 'Punjab',
                      21: 'Rajasthan',
                      22: 'Sikkim',
                      23: 'Tamil Nadu',
                      24: 'Uttar Pradesh',
                      25: 'Uttaranchal',
                      26: 'West Bengal'}

month_map = {
    0: "Jan",
    1: "Feb",
    2: "Mar",
    3: "Apr",
    4: "May",
    5: "Jun",
    6: "Jul",
    7: "Aug",
    8: "Sep",
    9: "Oct",
    10: "Nov",
    11: "Dec",
}
